### ISSUE TITLE
Wallet v2.0.2 crashes on startup after MacOS Mojave 10.14 upgrade

### ISSUE THREAD

**Issue by gCAN9** [muecoin/MUE#3]
After upgrading MacOS 10.13 (High Sierra) to 10.14 (Mojave) the wallet stopped working. It crashes directly after starting up. Occasionally it doesn't crash but instead freezes on loading, showing only the orange splash screen with the logo. 

**Machine specs:**
OS: MacOS 10.14
CPU: Intel Core i5 2.6 GHz
RAM: 8 GB
Disk size: 1.12 TB
Disk Type (HD/SDD): Fusion Drive HD+SSD

![screenshot 2018-12-04 at 14 54 38](https://user-images.githubusercontent.com/31687044/49447108-fbd5fd00-f7d5-11e8-87d5-ff3fba0e8612.jpg)
![screenshot 2018-12-04 at 15 00 46](https://user-images.githubusercontent.com/31687044/49447111-fe385700-f7d5-11e8-9c99-ab61caa60d3f.jpg)

**Comment by c44c** [comment]
Confirmed wallet crash on Mojave

**Comment by gCAN9** [comment]
While trying to build the wallet from the source and testing each time, I noticed that it did start up about 1-2 times from maybe 50 attempts. So it seems something in the startup sequence is causing the wallet to crash and this thing somehow doesn't get triggered each time, or when the wallet is started repeatedly after it crashes.

**Comment by gCAN9** [comment]
After further testing, additionally on another wallet that exhibits the same issue, I discovered that when forcing the wallet to start from scratch (by renaming folders _blocks, chainstate_, and wallet.dat) it helps a lot. The wallet then manages to start up and sync everything.

**Comment by gCAN9** [comment]
Issue seems to be resolved in v. 2.1.2

**Comment by c44c** [comment]
Glad its working now mate, Cheers!
