### ISSUE TITLE
2.1.1 Pre-Release on RPI fails to sync blockchain

### ISSUE THREAD

**Issue by c44c** [muecoin/MUE#7]
#### If so, please list the steps to reproduce below:
1. Install the 2.1.1 daemon and qt-client on a r-pi/raspbian system
2. Run the MUE QT-wallet
3. Chain gets stuck on block #140905. After closing the wallet, any attempt to use -reindex, -rescan or simply restart the wallet gives a seg fault.

### Expected behavior
Tell us what should happen
1. The 2.1.1 wallet gets stuck on block 140905, while the 2.0.2 wallet does not.

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![screenshot from 2018-12-13 13-06-51](https://user-images.githubusercontent.com/20333639/49937754-172cc080-fed8-11e8-9457-8d2f9e29e4ec.png)

### What version of MonetaryUnit Core are you using?
https://github.com/muecoin/MUE/releases/download/v2.1.1/mon-2.1.1-arm-linux-gnueabihf.tar.gz

### Machine specs:
- OS: Raspbian Stretch with desktop / Image with desktop based on Debian Stretch / Version:November 2018 / Release date:2018-11-13 / Kernel version:4.14
- CPU: ARM
- RAM: 1GB
- Disk size: 16GB
- Disk Type (HD/SDD): SD card

### Any extra information that might be useful in the debugging process.
After crashing / seg fault, removal of the blockchain and chainstate data allows the QT wallet to start again, and re-download the blockchain again, and then again get stuck on block #140905.

**Comment by c44c** [comment]
![screenshot from 2018-12-14 23-09-44](https://user-images.githubusercontent.com/20333639/50032609-6b799280-fff5-11e8-83ad-4464b15156de.png)

Restarted the wallet again:
The client is banning all other peers thus not progressing with the sync of the blockchain. Tested unbanning and cleaning the banned list, however all connected peers get added to the banlist again.

**Comment by tohsnoom** [comment]
Can you possibly give me the block hash of the latest block it has loaded?

Also, have you tried deleting the local blockchain folders (blocks, chainstate, sporks) and letting it sync again?

Also, would you be able to share the log file from around the time it loaded that block onward, so I can see any error messages or other information that may help diagnose the issue?

**Comment by c44c** [comment]
![image](https://user-images.githubusercontent.com/20333639/50051099-21cf9b80-010c-11e9-9c75-9ac77b7e0838.png)
updated 2.1.2 fixed the issues with an error with _checkpoint lock-in at 140906_ :+1: 
This issue can be closed now
